---
- hosts: localhost
  connection: local

  tasks:
    - name: Print the ENV and facts
      debug:
        msg: 
        - "SN_USERNAME: {{ SN_USERNAME }}"
        - "SN_HOST: {{ SN_HOST }}"
        - "sn_username {{ sn_username }}"
        - "sn_host: {{ sn_host }}"


