---
- hosts: localhost
  connection: local

  tasks:
    - name: Print the ENV and facts
      debug:
        msg: 
        - "SN_USERNAME: {{ lookup('env','SN_USERNAME') }}"
        - "SN_HOST: {{ lookup('env','SN_HOST') }}"


    - name: 
      shell: env | sort
      register: all_os_vars

    - name: assign the env vars to a fact
      debug:
        msg: 
        - "all_os_vars: {{ all_os_vars }}"
